### ISSUE TITLE
'pytorch_lightning.loggers' has no attribute 'TestTubeLogger'

### ISSUE THREAD

**Issue by TristanMorelle** [rinongal/textual_inversion#44]
continuing from my previous attempts i now get this error, apparently pytorch has removed this module 'TestTubeLogger'.

also tried installing the setup.py requirements for the torch  version
pytorch-lightning==1.5.9
pytorch=1.10.2

tried both:

python3 main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume models\ldm\stable-diffusion-v1\model.ckpt -n FireballRun --data_root object\artstyle\scene --gpus 1 --init-word TrainedFireball

python3 main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n FireballRun --data_root object\artstyle\scene --gpus 1 --init-word TrainedFireball

```
Restored from models\ldm\stable-diffusion-v1\model.ckpt with 0 missing and 2 unexpected keys
Unexpected Keys: ['model_ema.decay', 'model_ema.num_updates']
Traceback (most recent call last):
  File "D:\Workspace\textual_inversion-main\main.py", line 646, in <module>
    trainer_kwargs["logger"] = instantiate_from_config(logger_cfg)
  File "D:\Workspace\textual_inversion-main\ldm\util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs)
  File "D:\Workspace\textual_inversion-main\ldm\util.py", line 93, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'pytorch_lightning.loggers' has no attribute 'TestTubeLogger'. Did you mean: 'NeptuneLogger'?
```

**Comment by TristanMorelle** [comment]
did a total fresh env install with the same error as result
conda env create -f environment.yaml  naming the env different.

**Comment by rinongal** [comment]
Ok, so the python at `C:\Users\MyName.conda\envs\ldmt\python.exe` is what you actually want, yes.

On the gpu errors, per the readme, `--gpus xxxx` this is a list of GPU indices that you want to use, not the number of gpus. So if you have only a single GPU, you should be using `--gpus 0,`.

I don't have a good guide for windows errors, but you can try to follow the steps [here](https://www.reddit.com/r/StableDiffusion/comments/wucvgv/comment/il9vqta/?utm_source=share&utm_medium=web2x&context=3) (I wouldn't comment out the `assert torch.count_nonzero(tokens - 49407) == 2...` line).

You can also have a look here: #12. And here: [#14 ](https://github.com/rinongal/textual_inversion/issues/41#issuecomment-1231861338)

**Comment by TristanMorelle** [comment]
added these lines

`import signal
import platform
if platform.system() == 'Windows':
    os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"
    signal.signal(signal.SIGTERM, melk)
    signal.signal(signal.SIGTERM, divein)
else:
    signal.signal(signal.SIGUSR1, melk)
    signal.signal(signal.SIGUSR2, divein)`
    
Then this code did run:
python main.py --base configs/latent-diffusion/txt2img-1p4B-finetune.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n FireballRun --data_root object\artstyle\scene --gpus 1 --init-word TrainedFireball

can i use this output with stable diffusion?
-------------------------------------------------------------

This did not run and gave me the following error:
python main.py --base configs/stable-diffusion/v1-finetune.yaml -t --actual_resume models\ldm\stable-diffusion-v1\model.ckpt -n FireballRun --data_root object\artstyle\scene --gpus 0 --init-word TrainedFireball



`Project config
model:
  base_learning_rate: 0.005
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: false
    embedding_reg_weight: 0.0
    unfreeze_model: false
    model_lr: 0.0
    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings:
        - '*'
        initializer_words:
        - sculpture
        per_image_tokens: false
        num_vectors_per_token: 1
        progressive_words: false
        embedding_manager_ckpt: ''
        placeholder_tokens:
        - '*'
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
    ckpt_path: models\ldm\stable-diffusion-v1\model.ckpt
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: train
        per_image_tokens: false
        repeats: 100
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: val
        per_image_tokens: false
        repeats: 10
--init-word: null
TrainedFireball: null

Lightning config
modelcheckpoint:
  params:
    every_n_train_steps: 500
callbacks:
  image_logger:
    target: main.ImageLogger
    params:
      batch_frequency: 500
      max_images: 8
      increase_log_steps: false
trainer:
  benchmark: true
  max_steps: 6100
  accelerator: ddp
  gpus: 0


  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 859 M
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 123 M
3 | embedding_manager | EmbeddingManager   | 1.5 K
---------------------------------------------------------
768       Trainable params
1.1 B     Non-trainable params
1.1 B     Total params
4,264.947 Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]C:\Users\Tristan\.conda\envs\ldmt\lib\site-packages\pytorch_lightning\trainer\data_loading.py:132: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 32 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Validation sanity check:   0%|   `


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

**Comment by rinongal** [comment]
Looks like this is the same error as the person [here](https://github.com/rinongal/textual_inversion/issues/9), however they did not respond. 

I don't have any environment where this happens, but I'd be happy to try debugging it with you for future users if you have the patience for this.

Could you try printing the device of the token embedder (with something like print(next(self.token_embedding.parameters()).device)) and the device of the input_ids (print(input_ids.device)) before line 181 in `modules.py` and letting me know what you get?

**Comment by rinongal** [comment]
Looks like the model isn't running on your GPU for some reason. For example if you look at your latest output, it says:
GPU available: True, used: False

What parts of the gpu argument code did you modify? 
Also - if you prefer to do this on discord so we can have quicker turnaround times, my handle is Sylvver#2478

**Comment by rinongal** [comment]
Ok, so first of all with your change in the code, if you pass `--gpus 0` then this code bit will have ngpu = 0 which means no GPU. In the above commands you posted that you used `--gpus 1` for the LDM run, which is indeed what you want with this change.

The alternative is restoring the code in that block to the old version and running with `--gpus 0,` including the comma.

So to summerize:
Either keep the current code and use `--gpus 1` or return to old code and use `--gpus 0,`.

**Comment by rinongal** [comment]
Yep. You can reduce the batch size in the config (set `batch_size: 1` both places it appears in). 

If you do this, you might want to also add: `accumulate_grad_batches: 2` to the trainer block at the bottom.

**Comment by TristanMorelle** [comment]
ok so in "textual_inversion-main\configs\stable-diffusion\v1-finetune.yaml" i set the following:

```
model:
  base_learning_rate: 5.0e-03
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    embedding_reg_weight: 0.0
    unfreeze_model: False
    model_lr: 0.0

    personalization_config:
      target: ldm.modules.embedding_manager.EmbeddingManager
      params:
        placeholder_strings: ["*"]
        initializer_words: ["sculpture"]
        per_image_tokens: false
        num_vectors_per_token: 1
        progressive_words: False

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: train
        per_image_tokens: false
        repeats: 100
    validation:
      target: ldm.data.personalized.PersonalizedBase
      params:
        size: 512
        set: val
        per_image_tokens: false
        repeats: 10

lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 500
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_steps: 6100
    accumulate_grad_batches: 2
```
